# Generated by Django 3.2.7 on 2021-09-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('black', 'black'), ('white', 'white')], max_length=20)),
                ('piece_type', models.CharField(choices=[('pawn', 'pawn'), ('bishop', 'bishop'), ('knight', 'knight'), ('rook', 'rook'), ('queen', 'queen'), ('king', 'king')], max_length=20)),
            ],
        ),
    ]
