# Generated by Django 3.2.7 on 2021-09-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows', models.PositiveIntegerField(default=8)),
                ('cols', models.PositiveIntegerField(default=8)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
